### ISSUE TITLE
Why is there a G1::one() in reference-04-curve-operations?

### ISSUE THREAD

**Issue by yueawang** [CodaProtocol/snark-challenge#5]
https://github.com/CodaProtocol/snark-challenge/blob/81aa0f1188bbeac7916f6ef498e0185d85ede376/reference-04-curve-operations/libff/main.cpp#L137
https://github.com/CodaProtocol/snark-challenge/blob/81aa0f1188bbeac7916f6ef498e0185d85ede376/reference-04-curve-operations/libff/main.cpp#L138

Hi,

I am very confused by this reference code, the challenge asks for "h4_1 == g4_1[0] + g4_1[1] + ... + g4_1[n - 1]", but here reference result becomes "one+g4_1[0] + g4_1[1] + ... + g4_1[n - 1]". Is there a way making one+P==P ?
I am new to this whole EC theory, so maybe there is something wrong in my understanding.
Thanks!

**Comment by rbkhmrcr** [comment]
You're right, and this is fixed by #8. Thanks for pointing it out!
